Maksym.Demianovskyi
Kernel-GL-HRK/gl-android-training-2020 pull request #16
Opened 2020-04-22 07:53 UTC by m1ks-wq

2020-04-24 09:37 UTC, an1kh requested changes
Also please reword commit titles according to presentation
e.g. 02-Git: Add instead of added and so on.

2020-04-24 09:37 UTC, an1kh commented on 02-Git/CMakeLists.txt
> +add_executable(02-Git main.cpp)
no empty line at the end of the file

2020-04-24 09:37 UTC, an1kh commented on 02-Git/main.cpp
> +}
no empty line at the end of the file

2020-04-24 14:12 UTC, m1ks-wq commented
> Also please reword commit titles according to presentation
> e.g. 02-Git: Add instead of added and so on.

reworded

2020-04-24 14:13 UTC, m1ks-wq commented on 02-Git/CMakeLists.txt
> +add_executable(02-Git main.cpp)
added

2020-04-24 14:13 UTC, m1ks-wq commented on 02-Git/main.cpp
> +}
added

2020-04-27 06:29 UTC, an1kh requested changes
Also commit " 02-Git: implemented rock-paper-scissors console game" still has incorrect title.

2020-04-27 06:29 UTC, an1kh commented on 02-Git/main.cpp
> -}
Empty line is removed in last commit. please remove it first commit.
So this particular change will disappear.

2020-04-27 14:40 UTC, an1kh approved these changes
Well done! Please merge

2020-04-27 15:21 UTC, merged