Volodymyr Kulbashevsky's java service skeleton homework
Kernel-GL-HRK/gl-android-training-2020 pull request #20
Opened 2020-05-20 18:56 UTC by Coolbash

GL Android procamp HomeWork03: java service skeleton (service + getter app + setter app).

2020-05-25 13:15 UTC, BulldozerBSG requested changes
Please use android code style

2020-05-25 13:15 UTC, BulldozerBSG commented on 03-JavaServiceSkeleton/Setter/app/src/main/java/com/my1st/setter/MainActivity.java
> +        if(my1st_service != null)
Not a good idea to wrap the call unbindService() in a pointer check to null
From docs: If bindService() return true, you should later call unbindService(ServiceConnection) to release the connection.
In this case, just remove the check

2020-05-25 13:15 UTC, BulldozerBSG commented on 03-JavaServiceSkeleton/Getter/app/src/main/java/com/my1st/getter/MainActivity.java
> +        if(my1st_service != null)
Not a good idea to wrap the call unbindService() in a pointer check to null
From docs: If bindService() return true, you should later call unbindService(ServiceConnection) to release the connection.
In this case, just remove the check

2020-05-25 19:15 UTC, Coolbash commented
> 
> 
> Please use android code style

What is Android code style? Maybe I forgot something but I don't recall anybody told us anything about Android code style...

2020-05-25 20:17 UTC, BulldozerBSG commented
> > Please use android code style
> 
> What is Android code style? Maybe I forgot something but I don't recall anybody told us anything about Android code style...

The code is written in a different style:
The curly brace opens on the same line, then on a new one.
In places there is a space between operators and brackets, in places there is no.
Therefore, I proposed to bring everything to one style of source code

2020-05-25 20:20 UTC, BulldozerBSG commented
Examples of code style:
https://source.android.com/setup/contribute/code-style
or
https://google.github.io/styleguide/javaguide.html

2020-05-25 20:24 UTC, BulldozerBSG commented
As an option, use automatic code formatting in the Android Studio
https://developer.android.com/studio/intro/?gclid=EAIaIQobChMIvqzkx-vP6QIVRoGyCh3XCwebEAAYASAAEgLOMvD_BwE&gclsrc=aw.ds#style_and_formatting

2020-05-26 11:07 UTC, Coolbash commented
> As an option, use automatic code formatting in the Android Studio
> https://developer.android.com/studio/intro/?gclid=EAIaIQobChMIvqzkx-vP6QIVRoGyCh3XCwebEAAYASAAEgLOMvD_BwE&gclsrc=aw.ds#style_and_formatting

done

2020-05-26 12:47 UTC, BulldozerBSG approved these changes
Reviewed. No comments

2020-05-27 09:32 UTC, merged