03 java services
Kernel-GL-HRK/gl-android-training-2020 pull request #26
Opened 2020-05-25 20:20 UTC by m1ks-wq

2020-05-26 14:48 UTC, BulldozerBSG requested changes

2020-05-26 14:48 UTC, BulldozerBSG commented on 03-JavaServiceSkeleton/SetterApp/app/src/main/java/com/example/setterapp/MainActivity.java
> +                    int x = Integer.valueOf(sx);
What happens if sx contains no number?

2020-05-26 14:48 UTC, BulldozerBSG commented on 03-JavaServiceSkeleton/SetterApp/app/src/main/java/com/example/setterapp/MainActivity.java
> +                    myService.add(x);
What happens if mService contains null?

2020-05-26 14:48 UTC, BulldozerBSG commented on 03-JavaServiceSkeleton/GetterApp/app/src/main/java/com/example/getterapp/MainActivity.java
> +                    edtX.setText(String.valueOf(myService.get()));
What happens if mService contains null?

2020-05-28 12:23 UTC, m1ks-wq commented on 03-JavaServiceSkeleton/SetterApp/app/src/main/java/com/example/setterapp/MainActivity.java
> +                    int x = Integer.valueOf(sx);
Fixed.

2020-05-28 12:23 UTC, m1ks-wq commented on 03-JavaServiceSkeleton/GetterApp/app/src/main/java/com/example/getterapp/MainActivity.java
> +                    edtX.setText(String.valueOf(myService.get()));
Fixed.

2020-05-28 12:23 UTC, m1ks-wq commented on 03-JavaServiceSkeleton/SetterApp/app/src/main/java/com/example/setterapp/MainActivity.java
> +                    myService.add(x);
Fixed.

2020-05-29 17:54 UTC, BulldozerBSG approved these changes

2020-06-01 05:06 UTC, merged